version: '3'

services:
  php:
    build: ./docker/php
    ports:
      - 8000:80
    volumes:
      - ./backend:/backend
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    working_dir: /backend
    depends_on:
      - db

  composer:
    build: ./docker/composer
    volumes:
      - ./backend:/app:cached
    command: install
  
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./backend:/backend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /backend
    depends_on:
      - php
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      #- ./docker/db/sql:/docker-entry-point-initdb.d

volumes:
  db-data: